version: '2'
services:
  mongodb:
    container_name: mongo
    build: mongo/.
    image: codiez
    ports:
      - "27017:27017"
    command: mongod --smallfiles
  web:
    container_name: schools-service
    image: school-service-image:latest
    volumes:
      - /c/git/FinalEclipse/springwithDocker/spring-boot-demo/:/app/springboot
    depends_on: # schools-datastore will be started before the schools-service
      - mongodb
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test

  elasticsearch:
    build: elk/elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    links:
      - web  
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      
  logstash:
    build: elk/logstash/
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "9999:9999"
    links:
      - elasticsearch

  kibana:
    build: elk/kibana/
    container_name: kibana
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch    
      

